domain_url: 'http://www.diyiapp.com'

soft:
  url: 'http://www.diyiapp.com/azrj/{shsy|llyd|txpz|ztmh|yybf}/'
  list:
    node: '//ul[@class="pl"]/li/div[1]/a'
    href: './@href'
  content:
    title: '/html/head/title/text()'
    soft_name: '//h1/text()'
    keywords: '//meta[@name="keywords"]/@content'
    description: '//meta[@name="description"]/@content'
    category': '//div[@class="breadcrumb"]/a[3]/text()'
    image': '//div[@class="param"]/div[1]/p/img/@src'
    images: '//div[@id="screen_show"]//img/@src'
    content: '//div[@class="des"]'
    downfiles: '//div[@class="downlist"]/ul/li[1]/a/@href'
    filesize: '//ul[@class="param-ul"]/li[1]/span/text()'
    version: '//div[@class="param"]/div[1]/span/text()'
    release_at: '//ul[@class="param-ul"]/li[6]/span/text()'