domain_url: 'http://www.downyi.com'
middleware_func: 'foo'

soft:
  url: 'http://www.downyi.com/anzhuo/s_{297|299|295|300|301|298|296}_1.html'
  list:
    node: '//ul[@class="pl"]/li/div[1]/a'
    href: './@href'
  content:
    title: '/html/head/title/text()'
    soft_name: '//h1/text()'
    keywords: '//meta[@name="keywords"]/@content'
    description: '//meta[@name="description"]/@content'
    category': '//div[@class="breadcrumb"]/a[3]/text()'
    image': '//div[@class="param"]/div[1]/p/img/@src'
    images: 'array://div[@id="screen_show"]//img/@src'
    content: '//div[@class="des"]'
    downfiles: '//div[@class="downlist"]/ul/li[1]/a/@href'
    filesize: '//ul[@class="param-ul"]/li[1]/span/text()'
    version: '//div[@class="param"]/div[1]/span/text()'
    release_at: '//ul[@class="param-ul"]/li[6]/span/text()'
  process:
    title:
      trim:
        - '- 当易网'
    keywords:
      replace:
        - ',': '-'
    description:
      replace:
        - '当易网': '本站'
    content:
      trim:
        - 'trim'
      replace:
        - '当易网': '本站'

news:
  url: 'http://www.downyi.com/news/s_{297|299|295|300|301|298|296}_1.html'
  list:
    node: '//ul[@class="pl"]/li/div[1]/a'
    href: './@href'
  content:
    title: '/html/head/title/text()'
    article_title: '//h1/text()'
    keywords: '//meta[@name="keywords"]/@content'
    description: '//meta[@name="description"]/@content'
    content: '//div[@class="newsinfor"]'
    image: '//div[@class="newsinfor"]/p[2]//img/@src'