domain_url: 'https://www.7k7k7.com.cn/'

soft:
  urls:
    - 'https://www.7k7k7.com.cn/game/{71|8|6|28|7|27|24|23|15}_1_1/'
    - 'https://www.7k7k7.com.cn/soft/{29|32|35|33|42|30|19|44|9}_1_1/'
  list:
    node: '//div[@class="list"]/ul/li'
    href: './a/@href'
  content:
    title: '/html/head/title/text()'
    soft_name: '//h1/text()'
    keywords: '//meta[@name="keywords"]/@content'
    description: '//meta[@name="description"]/@content'
    category: '//div[@class="text"]/p[1]/span/text()'
    image: '//div[@class="labbox"]/div[@class="img"]/img/@data-original'
    images: 'array://ul[@class="snapShotCont"]//img/@src'
    content: 'html://div[@class="cont9"]/div[2]'
    downfiles: '//div[@class="downbtnbox"]/a/@href'
    filesize: '//div[@class="text"]/p[4]/span/text()'
    version: '//div[@class="text"]/p[3]/span/text()'
    release_at: ''
  process:
    title:
      trim:
        - '_7k7k7游戏网'
        - '7k7k7游戏网'
    description:
      replace:
        - '7k7k7游戏网': '本站'
    content:
      trim:
        - 'trim'
      replace:
        - '7k7k7游戏网': '本站'